### ISSUE TITLE
Comparison with official Google chat client?

### ISSUE THREAD

**Issue by geekdave** [seibert-media/go-hangouts#1]
Hello!

First of all, thanks for putting this project out there!  

In the [hangouts chat docs](https://developers.google.com/hangouts/chat/how-tos/libraries), there is a reference to an official google chat client library for go: https://github.com/google/google-api-go-client/tree/master/chat/v1

This library is auto-generated, so it's a bit messy but it does seem to be feature complete.

I was wondering if you had any experience with this official library, and if you were aware of any pros/cons of using each.  Just trying to understand the best place to get started.

Thanks!

**Comment by kwiesmueller** [comment]
Hey Dave,
when we/I started building this package for our experiments with the Jira Server bot, I did not find the autogen library yet.
After that porting to the official one was a bit too messy.

I work with the official Google Packages a lot, but tbh. the ones for Chat are a mess and for now I am much happier with the way we can build messages with our package.

It is possible that we still got errors or lack of updates when Google changes their Api but we want to maintain this as long as we see it as more useful for our daily work than the Google lib.
We are using this in 2 internal projects as well and just yesterday I gave the official libs another look to check if using them would be better there, but I ended up simply sending the messages built with our package via webhooks in the end because it is just 3 lines of code to use the webhook.

For sending messages we either use PubSub or WebHooks, I did not see either in v1/chat so the only part useful for us there would be building messages and that we got covered here as we need it.

If you are looking for a lib to choose, I would be happy for somebody using this project and contributing both feedback and maybe code, but this is no project that is highly maintained by us and mostly I have been involved here alone, so I can not guarantee anything except my motivation for now.

**Comment by kwiesmueller** [comment]
Our bot needs some revamp as well, which we are on but time is an issue 😉
But you can check it out: https://github.com/seibert-media/hangouts-jira-bot

**Comment by kwiesmueller** [comment]
Oh and the logging part we use here will get changed soon as we reworked the library used for this and got a much cleaner approach now (https://GitHub.com/seibert-media/golibs)
Will come in the next week or 2 so this might make using the lib easier for you as well

**Comment by geekdave** [comment]
@kwiesmueller Awesome - I really appreciate this insight!  I've currently got a hand-rolled solution for sending plain text messages to the google chat webhook endpoint.  Next, I want to send card-formatted messages.

Might you be able to provide a simple example of using your library to construct a card and send it to the webhook API?

**Comment by kwiesmueller** [comment]
I added this example: https://github.com/seibert-media/go-hangouts/blob/master/examples/webhook-card/main.go

The current sending process is quite primitive, but works.
I would be happy to make changes there if you got suggestions.

The process of building a message is okay, but not that much different from creating it by hand, but I saw it helps to prevent building invalid messages.
Make sure to use the latest commit, I also took the time when writing the example and fixed the logging. You should now be able to use the lib without being forced to use our logging.

**Comment by geekdave** [comment]
Thanks so much @kwiesmueller !  I'll give this a try and report back.  I appreciate your time putting together the example.  Very helpful for me as a golang newbie. 😄

**Comment by m0un10** [comment]
Just chiming in to say thanks for the webhook card example @kwiesmueller. 
Helped me too and worked on first try :) 
(Once I realised I needed to put the url in double quotes when calling from bash to prevent an issue caused by % character.)

**Comment by geekdave** [comment]
Hey @kwiesmueller - Finally getting around to trying this.  But it still seems to be dependent on your logging framework.  This line expects a `ctx` object which appears to come from an earlier call to `ctx := log.WithLogger(context.Background(), log.New("", true))`, which uses your log framework.  I can't seem to pass as `nil` without the call hanging:

https://github.com/seibert-media/go-hangouts/blob/master/examples/webhook-card/main.go#L54

Any tips for calling Send without your logs?

Edit: I'm a go n00b, so I might be missing something obvious.  I see that the `Send` method takes a `Context` object which might not require your logging framework, but I'm not sure how I'd create one without it.  Any quick tips would be much appreciated 😄

**Comment by kwiesmueller** [comment]
Passing a context is a pretty common practice in go.
You can simply use a fresh context (`context.Background()`) if you haven't got one in your architecture.

**Comment by kwiesmueller** [comment]
If the context doesn't contain our logger it is being ignored and you won't get an error because of this.
We just expect context to be there because we follow this practice when building our services.

See https://blog.golang.org/context

**Comment by geekdave** [comment]
@kwiesmueller `context.Background()` did the trick!  I've got your library integrated with our alerting system now!  Thanks for the pointer about the best practices on contexts.  I'll add this to my reading list. :)  Once again I really appreciate your help!  Looking forward to continuing to collaborate on this project!
